### ISSUE TITLE
Pythonization of python bindings

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#100]
@pandeyhs, the remaining work (You can keep using the same branch, I'll leave it open):

* [ ] Fix the examples with 🔶 on #111 
* [x] Add `""_a` names on as many bindings as possible
* [ ] Verify all PDF constructors have a matching number of bindings

Optional:
* Add documentation strings. After each `.def` name and function, a docstring can be added:

```cpp
    R"raw(
    This is some help.

    This is really long help.
    )raw"
```

* Add useful python special methods, like `__len__`, `__str__`, `__repr__`, etc.

**Comment by thboettc** [comment]
Closing this, as what's left can be superseded by https://github.com/GooFit/GooFit/issues/332
