### ISSUE TITLE
cannot build on compute 6.1 

### ISSUE THREAD

**Issue by nicolin** [GooFit/GooFit#101]
Hi, would it be possible to specify the compute you want to build as currently it fails on the latest Pascal cards.

Btw: i am willing to help with any CUDA code, i have a GPU research center and have a good relationship with NVIDIA as i have been working on CUDA apps with them since 2009. 

Cheers

[  3%] Building NVCC (Device) object src/goofit/CMakeFiles/FitManager1.dir/FitManager1_generated_FitManagerMinuit1.cc.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at FitManager1_generated_FitManagerMinuit1.cc.o.RelWithDebInfo.cmake:222 (message):
  Error generating
  /home/nicolin/bin/sw/GooFit/build/src/goofit/CMakeFiles/FitManager1.dir//./FitManager1_generated_FitManagerMinuit1.cc.o

src/goofit/CMakeFiles/FitManager1.dir/build.make:63: recipe for target 'src/goofit/CMakeFiles/FitManager1.dir/FitManager1_generated_FitManagerMinuit1.cc.o' failed
make[2]: *** [src/goofit/CMakeFiles/FitManager1.dir/FitManager1_generated_FitManagerMinuit1.cc.o] Error 1
CMakeFiles/Makefile2:282: recipe for target 'src/goofit/CMakeFiles/FitManager1.dir/all' failed
make[1]: *** [src/goofit/CMakeFiles/FitManager1.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by henryiii** [comment]
Sure, try `-DGOOFIT_ARCH=6.0` on the CMake step. I've tested it with 6.0 and 6.2, but don't have a 6.1 card so haven't tested that.

Thanks, help is always appreciated!

**Comment by henryiii** [comment]
What version of CUDA are you using? You need 8.0 for a Arch 6 card. That error sounds like it's from NVCC before it even tries to compile.

**Comment by nicolin** [comment]
Thanks I am using CUDA 7.5, i have added the flag to compile for SM 5.2 it
has gone past that point now about 23% built.

I was doing my own port of roostats for limit setting using  StdHypoInv but
it is so tedious  to navigate thru the chain in  root and then putting each
of those on GPU....
So this will make a lot less work for me.

Cheers

**Comment by nicolin** [comment]
Ok, crashing at this now:


GooFit/examples/2d_plot/2d_plot.cu(46): error: identifier "kViridis" is
undefined

1 error detected in the compilation of
"/tmp/tmpxft_0000533d_00000000-7_2d_plot.cpp1.ii".
CMake Error at 2d_plot_generated_2d_plot.cu.o.RelWithDebInfo.cmake:282
(message):
  Error generating file

/home/nicolin/bin/sw/GooFit/build/examples/2d_plot/CMakeFiles/2d_plot.dir//./2d_plot_generated_2d_plot.cu.o


examples/2d_plot/CMakeFiles/2d_plot.dir/build.make:63: recipe for target
'examples/2d_plot/CMakeFiles/2d_plot.dir/2d_plot_generated_2d_plot.cu.o'
failed
make[2]: ***
[examples/2d_plot/CMakeFiles/2d_plot.dir/2d_plot_generated_2d_plot.cu.o]
Error 1
CMakeFiles/Makefile2:684: recipe for target
'examples/2d_plot/CMakeFiles/2d_plot.dir/all' failed
make[1]: *** [examples/2d_plot/CMakeFiles/2d_plot.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by henryiii** [comment]
You can turn off the examples if you need to. KViridis is from a pretty recent version of ROOT. What version are you using?

**Comment by nicolin** [comment]
Ok thanks root   6.04 .

got a little further now :-)

In file included from
/home/nicolin/bin/sw/GooFit/extern/generics/generics/detail/alias.h:2:0,
                 from
/home/nicolin/bin/sw/GooFit/extern/generics/generics/ldg.h:2,
                 from
/home/nicolin/bin/sw/GooFit/include/goofit/GlobalCudaDefines.h:57,
                 from
/home/nicolin/bin/sw/GooFit/include/goofit/Variable.h:8,
                 from
/home/nicolin/bin/sw/GooFit/python/goofit/Variable.cpp:2:
/home/nicolin/bin/sw/GooFit/extern/generics/generics/detail/array.h:13:25:
error: ‘__forceinline__’ does not name a type
     __host__ __device__ __forceinline__

**Comment by henryiii** [comment]
I was about to warn you, on master you have to turn off the Python bindings, they don't interact with CUDA correctly yet. `-DGOOFIT_PYTHON=OFF`. I should not have changed the default to on yet. Stable is fine.

**Comment by henryiii** [comment]
I've just reverted the default in the latest (about to be merged) PR.

**Comment by nicolin** [comment]
Thanks, i am doing the install on opensuse and have had issues with finding
root libs, when i was last at CERN we managed to get it working but since
there have been issues with root.
I now get an error with -lROOT::Minuit2 , i did see on the webpage that
Minuit2 will be built without root if it is not found.

Have you tried using nsight for the project, i will give this a try once i
have managed to build it.

Cheers

**Comment by henryiii** [comment]
It searches for ROOT, and only builds Minuit2 if ROOT is not found. Haven't thought about or tried it with ROOT that doesn't have Minuit2; I would think that's pretty easy to do with a few changes to the CMakeLists.txt. Haven't tried NSight on a non-Windows platform. Let me know how it goes. I know CMake 3.9 is recommended for NSight on Windows, not sure about non-Windows.

**Comment by henryiii** [comment]
PS: I'm about to drive to Fermilab, so will not be able to respond for a while.

**Comment by nicolin** [comment]
Dear Henry

Thanks, i have used only nsight on linux for CUDA since 2010 it makes
optimization much easier and full syntax highlighting for GPU code.
Ok i will modify the CMake file to build Minuit.  Actually my current ROOT
has built any libs i am not sure why....

Sure.

Cheers

**Comment by henryiii** [comment]
See if a change like I've added to #103 works for you. And, let me know how this works with NSight/Eclipse, I assume it should be well supported under CMake. I've tested Xcode, CLion, and QtCreator.

**Comment by nicolin** [comment]
Dear Henry

Thanks, i will try it with nsight this weekend.

In file included from
/home/nicolin/bin/sw/GooFit/src/goofit/FitManagerMinuit1.cc:1:0:
/home/nicolin/bin/sw/GooFit/include/goofit/PdfBase.h:18:37: fatal error:
Minuit2/FunctionMinimum.h: No such file or directory
 #include <Minuit2/FunctionMinimum.h>
                                     ^
compilation terminated.
CMake Error at
FitManager1_generated_FitManagerMinuit1.cc.o.RelWithDebInfo.cmake:222
(message):
  Error generating

/home/nicolin/bin/sw/GooFit/build/src/goofit/CMakeFiles/FitManager1.dir//./FitManager1_generated_FitManagerMinuit1.cc.o

Cheers

**Comment by henryiii** [comment]
I'm testing it now with a OpenSUSE docker instance. Fixed a bug in `ROOT_FOUND` that was introduced with the recent Python merge. I'm working in the `fixes_nominuit` branch.

**Comment by nicolin** [comment]
Thanks much appreciated.

Cheers

**Comment by henryiii** [comment]
Try with current master. You might want to remove your build directory (or at least CMakeCache.txt) just to make sure you are starting fresh. Feel free to take a look at my instructions [here](https://github.com/GooFit/GooFit/blob/master/docs/SYSTEM_INSTALL.md) for ROOT instructions for OpenSUSE **after** you try with your current setup.

**Comment by nicolin** [comment]
Dear Henry

Thank you, you instruction for root also worked perfectly.
I am still having issues compiling stuff using root, any  help will be
greatly appreciated.

LikelihoodCalculator.cxx: In static member function ‘static Int_t
LikelihoodCalculator::FindErrors(const TH1D*, Double_t, const
std::vector<double>&, TMatrixD&, int, int)’:
LikelihoodCalculator.cxx:1073:35: error: no match for ‘operator=’ (operand
types are ‘TMatrixDRow {aka TMatrixTRow<double>}’ and ‘const Double_t {aka
const double}’)
             TMatrixDRow(xval,imin)= NaN;
                                   ^
LikelihoodCalculator.cxx:1073:35: note: candidates are:
In file included from /opt/root-6-10-04/include/TMatrixT.h:24:0,

Cheers

**Comment by henryiii** [comment]
What are you trying to do? `TMatrixDRow(mat, row)` is a constructor for a row. You can't set a whole row to a value. If that's what you want to do, use `.Assign(NaN)` instead.

**Comment by nicolin** [comment]
Hi, i have attached the code in the previous mail. It is a standard test
package that we are using:

Author: Tim Adye, based on
$ROOTSYS/tutorials/roostats/StandardHypoTestInvDemo.C

Thanks

**Comment by henryiii** [comment]
I don't see any usage `TMatrix`-anything in that file (at least in ROOT 6.10). I think, looking at your code,
```cpp
TMatrixDRow(xval,imin)= NaN;
```

can be replaced with

```cpp
TMatrixDRow(xval,imin).Assign(NaN);
```
I'm assuming `xval` is a matrix and that these lines modify the values in the row of the matrix.

**Comment by nicolin** [comment]
Thanks that worked, now i will filter thru the code and identify which
functions i need to put on the GPU to do the limit setting (toy monte
carlo)

Cheers

**Comment by henryiii** [comment]
Okay, I'm going to close this issue for now, since the problem(s) are hopefully fixed. Please feel free to ask if you run into anything else, or reopen the issue if needed. (And discussion can continue on a closed issue). You can also let me know even if everything works fine. :) Cheers!
