### ISSUE TITLE
Adding examples to Python

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#111]
The current examples converted:
- [x] Exponential ✅ 
- [x] Plot2D  ✅
- [x] Addition ✅
- [x] Convolution ✅
- [x] DP4 ✅
- [x] Product ✅
- [x] TDDP4(nice to have) ✅
- [x] dalitz ✅
- [x] SigGen ✅
- [x] Chisquare ✅
- [x] simpleFit ✅
- [x] zachFit ✅
- [ ] pipipi0 ❌

**Comment by henryiii** [comment]
Hint on debugging:
```bash
cmake .. -DGOOFIT_DEVICE=CPP -DGOOFIT_DEBUG=ON -DCMAKE_BUILD_TYPE=Debu
```

You could add `-DCMAKE_CXX_FLAGS_DEBUG="-g -O0" `, but might be overkill. Remember to change your PYTHONPATH if you are in a different directory!

Then:
```bash
gdb -tui -ex r --args python pyexamples/SigGen.py
```

**Comment by henryiii** [comment]
@pandeyhs , I've updated the examples and lists. Please go through and add `import sys` near the top and `sys.exit(int(int(fitter))` on the ones that use a fitter. I think I have an adaptor that allows a PDF to be converted to an int as well, but it's probably not bound. (I'll see if I can fix that double int soon)

**Comment by henryiii** [comment]
@pandeyhs Please attempt to finish simpleFit. I've gotten past the previous issues. Look at the changes in the PR that matter for Python, that might help.

**Comment by henryiii** [comment]
@pandeyhs `DecayInfo` (3,3t,4,4t), even though it is not a pointer, needs `py::keep_alive`, since it has pointers inside it (that end up pointing to python-created objects). I've added those, and that fixed `dalitz` and `chisquare`. SimpleFit and maybe zachFit are all that's left! Going to merge `py_dev_hsp` in an hour so master stays current. The python examples now run as part of Travis CI.

**Comment by thboettc** [comment]
Closing this. Superseded by https://github.com/GooFit/GooFit/issues/332
