### ISSUE TITLE
Fix recent breaking of zachFit

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#112]
The inclusion of #110 broke zachFit. Making the storage globally defined means you can only have one instance, which is not the case.

**Comment by galapaegos** [comment]
I would revert back temporarily.

The first fit converges successfully, the second fit crashes.  This is what you are seeing?

**Comment by henryiii** [comment]
I've reverted for the moment. The first fit (using `./zachFit 0 1`) "finishes", but gives large edm and NANs in the cov. matrix. The second fit fully crashes.
