### ISSUE TITLE
How can i generate a gaussian distribution with more than 10^9 events and fit it?

### ISSUE THREAD

**Issue by AbrahamReyes** [GooFit/GooFit#121]
I tried to make simple gaussian fit with 10^8 events but it threws me and error after running the program:
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  cudaEventSynchronize in future::wait: an illegal memory access was encountered
Aborted.

I generated the events by this way:

for(unsigned long int i = 0; i < 1000000000;++i){
    {                                                                               
        xvar.setValue( donram.Gaus(0.2,1.1));                                      
                                                                                
        if(donram.Uniform()<0.1)                                                 
           xvar.setValue(donram.Uniform(xvar.getLowerLimit(), xvar.getLowerLimit()));                                                                     
        if(fabs(xvar.getValue()) > 5)                                       
        {                                                                         
           --i;                                                                 
           continue;                                                            
        }                                                                          
                                                                                 
        data.addEvent();                                                            
        totalData++;                                                               
    }

**Comment by henryiii** [comment]
I believe that you've run out of space on your graphics card. If you use OMP (`-DGOOFIT_DEVICE=OMP` when building), you can do it.
