### ISSUE TITLE
Move to using official Eigen Mirror

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#135]
There is finally an official GitHub Eigen mirror, we should use that.

`eigenteam/eigen-git-mirror`

Moving to a different git repository is a pain, so this probably should be for GooFit 2.2.

**Comment by galapaegos** [comment]
@henryiii 

I have fix for this, but using the bleeding edge from Eigen which has the changes for CUDA 9.1.  At some point we should point to a release.  This commit was pushed to newindexing.
