### ISSUE TITLE
New call structure diagram

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#155]
## Call structure

* `GooPdf` constructor - Only called once, at PDF creation
* `GooPdf::pre_run()` - called once before an evaluation series (parameters may change)
* `GooPdf::pre_call()` - Called before every evaluation
* `GooFit::normalize()`
    * `GooPdf::pre_normalize()` TBD
    * `GooPdf::user_normalize()` TBD
    * `GooPdf::post_normalize()` TBD
* Call (several different versions with different functors and transforms)
    * `GooPdf::per_point_evaluate()`
    * `GooPdf::reduce()`
* `GooPdf::post_call()` - Called after every call is done (cleanup options)
* `GooPdf::post_run()` - Called after a run sequence is over (cleanup)

### The job of a PDF
 * Store 1 attached dataset (or +1 for normalization?)
 * Store 1 attached cache (Should one be added for normalization?)
 * Holds pointer to evaluation function

 ### Combine PDFs
 * Store set of pointers to sub-PDFs (managed)
 * Knows how to normalize subcomponents

 ### Customizables
 * `generate()`
 * `integrate()`
 * `evaluate()`
 * `hasAnalyticIntegral()`

**Comment by thboettc** [comment]
This looks like it's done, so I'm closing it.
