### ISSUE TITLE
"cudaConfigureCall" is undefined when building v2.2 on CUDA10.1

### ISSUE THREAD

**Issue by jpazzini** [GooFit/GooFit#199]
I am trying to install GooFit v2.2 on a machine with a GeForce GTX 1080, CUDA 10.1, on a Ubuntu Linux distro.

I have first attempted the procedure reported in the documentation by [building the source](https://github.com/GooFit/GooFit#building) with a custom set of options to impose using CUDA, python bindings, etc.
I have however encountered issues, so I resorted to following the step-by-step the [build recipe](https://github.com/GooFit/GooFit/blob/master/docs/SYSTEM_INSTALL.md) for Ubuntu 18.04 LTS.

CMake is capable of correctly identify the presence of a CUDA compiler, the version of ROOT, the python interpreter and so on [1].
During the make step the error [2] occurs when building the `src/PDFs/CMakeFiles/PDFCore`, with the main message apparently being:
`identifier "cudaConfigureCall" is undefined`

Is this a known issue?
If this is the case, would reverting back to CUDA 9.X and using GooFit v2.1 make any difference?

[1]
```
pazzini@pazzini-EliteDesk800G4:~/GooFit/build$ cmake ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Submodule update
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda-10.1/bin/nvcc
-- Auto device selection: CUDA
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found CUDA LANGUAGE 10.1.105 at /usr/local/cuda-10.1/targets/x86_64-linux/include
-- Compiling for GPU arch: sm_61
-- Using Thrust from /usr/local/cuda-10.1/targets/x86_64-linux/include
-- Found ROOT: /usr/local/root/bin/root-config (Required is at least version "6") 
-- Found ROOT 6.17/01 at /usr/local/root/include
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Version: 5.3.0
-- Build type: RelWithDebInfo
-- CXX_STANDARD: 11
-- Performing Test has_std_11_flag
-- Performing Test has_std_11_flag - Success
-- Performing Test has_std_0x_flag
-- Performing Test has_std_0x_flag - Success
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Success
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Success
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Success
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Looking for open
-- Looking for open - found
-- Compiler supports IPO: NO
-- Downloading pipipi0 data files
-- [download 0% complete]
[...]
-- [download 100% complete]
-- Downloading zachFit data files
-- Found PythonInterp: /home/pazzini/anaconda3/bin/python (found version "3.7.3") 
-- Found PythonLibs: /home/pazzini/anaconda3/lib/libpython3.7m.so
-- Found Python at /home/pazzini/anaconda3/lib/libpython3.7m.so, building bindings
-- pybind11 v2.3.dev0
-- The following features have been enabled:

 * GOOFIT_DEVICE=CUDA, The device to compile for
 * GOOFIT_HOST=CPP, The host system to compile for
 * ARCH_FLAGS=sm_61, Readable GPU arch flags
 * GOOFIT_SPLASH, Show a unicode splash or a small plain text one
 * GOOFIT_TESTS, Build the goofit tests
 * GOOFIT_EXAMPLES, Build the example programs
 * GOOFIT_PACKAGES, Build any goofit_* packages found
 * GOOFIT_PYTHON, Python bindings for goofit

-- The following features have been disabled:

 * GOOFIT_KMATRIX, Activate support for KMatrix (slower CUDA builds)
 * GOOFIT_TRACE, Print messages to trace the behavior of GooFit
 * GOOFIT_DEBUG, Print debugging messages
 * GOOFIT_MPI, Turn on MPI for goofit
 * GOOFIT_TIDY_FIX, Perform fixes for Clang-Tidy - changes source inplace

-- The following packages have been found:

 * Backtrace
 * ROOT (required version >= 6)
 * PythonInterp

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pazzini/GooFit/build
```

[2]
```
pazzini@pazzini-EliteDesk800G4:~/GooFit/build$ cmake --build .
[...]
[  9%] Building CUDA object src/PDFs/CMakeFiles/PDFCore.dir/detail/Globals.cu.o
/home/pazzini/GooFit/extern/thrust/thrust/system/cuda/detail/bulk/detail/cuda_launcher/triple_chevron_launcher.hpp(127): error: identifier "cudaConfigureCall" is undefined

/home/pazzini/GooFit/extern/thrust/thrust/system/cuda/detail/bulk/detail/cuda_launcher/triple_chevron_launcher.hpp(180): error: identifier "cudaConfigureCall" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00002b9c_00000000-4_Globals.cpp4.ii".
src/PDFs/CMakeFiles/PDFCore.dir/build.make:62: recipe for target 'src/PDFs/CMakeFiles/PDFCore.dir/detail/Globals.cu.o' failed
make[2]: *** [src/PDFs/CMakeFiles/PDFCore.dir/detail/Globals.cu.o] Error 2
CMakeFiles/Makefile2:605: recipe for target 'src/PDFs/CMakeFiles/PDFCore.dir/all' failed
make[1]: *** [src/PDFs/CMakeFiles/PDFCore.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by henryiii** [comment]
The 1.8.1 version of thrust doesn't support CUDA 10.1, and we can't (yet) use the built-in or most recent GitHub thrust. CUDA 8,9, and 10.0 should be fine. You can (and should) use the latest GooFit even with an older Thrust. I'm hoping to work on some fixes and features in the next week or two.

**Comment by LLyq17** [comment]
Hi ,when i run make command in the build directory on my server,the errors occur!

1 error detected in the compilation of "/tmp/tmpxft_0001536d_00000000-6_GooPdf.cpp1.ii".
CMake Error at PDFs_generated_GooPdf.cu.o.RelWithDebInfo.cmake:279 (message):
  Error generating file
  /home/lq/GooFit/build/src/PDFs/CMakeFiles/PDFs.dir//./PDFs_generated_GooPdf.cu.o

make[2]: *** [src/PDFs/CMakeFiles/PDFs.dir/PDFs_generated_GooPdf.cu.o] Error 1
make[1]: *** [src/PDFs/CMakeFiles/PDFs.dir/all] Error 2

The cmake command is completed ,the following is output results! Thank u


-- Submodule update
-- Found CUDA 10.0 at /usr/local/cuda
-- Compiling for GPU arch: sm_75
-- Using Thrust from /usr/local/cuda/include
-- Found ROOT 6.14/04 at /usr/local/root/include
-- BUILD_TESTING is defined and it supersedes CLI11_TESTING. Has forced to OFF
-- Version: 5.3.0
-- Build type: RelWithDebInfo
-- CXX_STANDARD: 11
-- CMake <3.9 will only enable IPO for Intel compilers on Linux
-- Found Python at /usr/lib64/libpython2.7.so, building bindings
-- pybind11 v2.3.dev0
-- 
-- The following features have been enabled:

 * GOOFIT_DEVICE=CUDA , The device to compile for
 * GOOFIT_HOST=CPP , The host system to compile for
 * ARCH_FLAGS=sm_75 , Readable GPU arch flags
 * GOOFIT_SPLASH , Show a unicode splash or a small plain text one
 * GOOFIT_TESTS , Build the goofit tests
 * GOOFIT_EXAMPLES , Build the example programs
 * GOOFIT_PACKAGES , Build any goofit_* packages found
 * GOOFIT_PYTHON , Python bindings for goofit

-- The following features have been disabled:

 * GOOFIT_KMATRIX , Activate support for KMatrix (slower CUDA builds)
 * GOOFIT_TRACE , Print messages to trace the behavior of GooFit
 * GOOFIT_DEBUG , Print debugging messages
 * GOOFIT_MPI , Turn on MPI for goofit
 * GOOFIT_TIDY_FIX , Perform fixes for Clang-Tidy - changes source inplace

-- The following packages have been found:

 * Backtrace
 * Threads
 * CUDA (required version >= 7.0)
 * ROOT (required version >= 6)
 * PythonInterp

-- Configuring done
-- Generating done
-- Build files have been written to: /home/lq/GooFit/build

**Comment by henryiii** [comment]
Wow, that is really a very unhelpful error. What version of CMake are you using? Our support for CMake < 3.8 combined with CUDA is not as good as newer CMake + CUDA.

**Comment by LLyq17** [comment]
Thank you for your reply!The version of my cake is 3.7.0. Do you  mean  the version is too low?Do  I need to update it?
Thanks again


 
---Original---

**Comment by henryiii** [comment]
Try a recent version, just to see if that could be the problem. I've built GooFit + CUDA 10.0, but always with a version of CMake that had CUDA-as-a-language support

https://cliutils.gitlab.io/modern-cmake/chapters/intro/installing.html

**Comment by LLyq17** [comment]
Ok. I will try again!  Thank you!
 
---Original---

**Comment by thboettc** [comment]
It sounds like this issue is more or less solved. @LLyq17 feel free to reopen if I'm wrong.

**Comment by AdrianoDee** [comment]
I've stumbled upon this issue since I was getting the same error and at the end the origin was coming from the fact that on our cluster machine `cuda-11.0` is installed. A quick and trivial fix for this, without having to install `cuda-10.0`, is to install `goofit` via `conda` forcing the `cudatoolkit` to be `10.0` with

``` conda install goofit goofit-proc=*=gpu cudatoolkit=10.0 ```

This may be trivial for many but could help some.
