### ISSUE TITLE
Error when adding efficiency to Amp3Body

### ISSUE THREAD

**Issue by marthaisabelhilton** [GooFit/GooFit#216]
Dear GooFit experts,
When I try to add an efficiency to Amp3Body other than a constant PolynomialPdf, it does not work and I get the following error:
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: operation not supported on global/shared address space
Aborted
```
I have made a minimal working example in which I try to use SquareDalitzEfficiencyPdf in the Amp3Body.
[SquareDalitzEffPdf_test.py.txt](https://github.com/GooFit/GooFit/files/3875210/SquareDalitzEffPdf_test.py.txt)

I would appreciate it if someone could take a look.
Many thanks,
Martha

**Comment by mrwillia** [comment]
Dear experts. It would be great if someone can take a look at this. It does seem to be a general bug that no non-trivial efficiency can be incorporated into the Amp3Body PDF, which is clearly a problem. I see the recent issue from @JuanBSLeite (https://github.com/GooFit/GooFit/issues/217) mentions a slightly different but perhaps related problem - he also mentions that he can include efficiencies in his local branch, but not in the master.
