### ISSUE TITLE
Memory error when adding efficiency as SmoothHistogramPdf to Amp3Body

### ISSUE THREAD

**Issue by JuanBSLeite** [GooFit/GooFit#217]
Hello GooFit users and experts,

When I try to use SmoothHistogramPdf as efficiency to Amp3Body on GooFit master branch version I'm getting the following error message

`terminate called after throwing an instance of 'thrust::system::system_error'
  what():  an illegal memory access was encountered`

The same code works perfectly on my branch version.

Is there someone facing the same issue?
Thanks,
Juan

**Comment by marthaisabelhilton** [comment]
Hi all I think this might be the same issue as I mentioned in #216 ?
