### ISSUE TITLE
Dev planning

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#22]
These are my planned cleanups, in three steps:

1. Cleanup make system (dev branch)

- [x] Remove globbing and the non-deterministic build failures caused by this
- [x] Remove fake nvcc and similar kludges
- [x] Use a central Makefile for examples
- [x] Simplify switch to OMP to *only* adding `OMP_TARGET=1`
- [x] Automate running (and timing) of all examples as a test system
- [x] Add separate run lines for each test in `int_testing.py`
- [x] Fix 4 remaining examples that currently (also in master?) fail
    - [x] `dalitz`: `std::logic_error`, `basic_string::_S_construct` null not valid: Missing parameter (now has a default)
    - [x] `zachFit`: Was missing a file (nice error message now)
    - [x] `pipipi0DPFit`: Missing parameter (now gives nice error message)
    - [x] `chisquare`: Missing parameter (now has a default)
- [x] `let_testing.py` skips tests that are missing files

Done! See PR #23 . 

2. Move files to more traditional structure (new folders branch)

- [x] New structure, including:
```
include/goofit
include/goofit/PDFs
include/goofit/rootstuff
src/goofit
src/PDFs
src/rootstuff
```
- [x] Including goofit files (in goofit and examples) would be:
```
#include "goofit/MyGoofitHeader.h"
```
- [x] File extension normalized (one ext for cpp, one for cuda, and one for headers)
- [x] Added script to automate this for easy transitions
- [x] Clean up formatting with astyle, include style file `.astylerc`

Done! Now in the dev branch.

3. Move to CMake build system (better builds, make it easier to integrate Hydra ?

- [x] More compute capability choices, auto enables 3.5 extra features if possible, Auto option for GPU detection. Uses latest version of FindCUDA, supplied for CMake < 3.7
- [x] Optional separable compilation: cleaned up PDFs, added as option (on one system, multithreaded builds went from ~5 minutes to under 2 minutes)
- [x] Add auto Cuda/OMP option
- [x] Add Intel build
- [x] Add support for GooFit Packages
- [x] Allow packages/examples to add PDFs

Done! Now in the dev branch. 

4. Further questions:

- [x] Add documentation about building to readme
- [x] Remove unneeded warnings

Future work
- Look at including Hydra
- Look at setting up Travis CI (with low compute power tests!)
- Add TBB - too hard for now, due to use of THREADIDX, BLOCKIDX
- Improve separation of headers and source in PDFs
- Look at removing the separate docs branch, and use `docs` in `master` (now supported in GitHub)
- Make datafiles more readily available
- Use some sort of parser in the examples to improve option descriptions

**Comment by hassec** [comment]
Hi @henryiii ,


looks like a great plan! 
Just a quick note on the dalitz example, it seems like you missed that it needs to be run like `./dalitz dalitz_toyMC_000.txt`. Without the text file it will throw the error you mentioned above.

**Comment by henryiii** [comment]
Thanks @hassec, that was the problem. Added a default arg.

**Comment by galapaegos** [comment]
Hi @henryiii,

Dalitz and pipipi work fine.  Chisquare works with a parameter.  GPU/OMP toggling works out of the box minus the issues below.

ZachFit currently doesn't function due to the omp parallel calls causing multiple threads accessing the memory, PR#24 will fix this issue.  ZachFit with OMP will not work due to specific cuda calls.

**Comment by henryiii** [comment]
Thanks @galapaegos! I've fixed the (output) for the default parameter, and merged the PR. The only thing left is the odd zachFit behavior. It runs up to the print out of the coefficients, then just hangs and must be cancelled.

**Comment by galapaegos** [comment]
Hi @henryiii,

ZachFit is hanging on a missing file.  It is expecting 'dataFiles/zach/dstwidth_kpi_data.dat', but is only provided the 'dataFiles/dstwidth_kpi_resMC.dat'.

**Comment by henryiii** [comment]
Yes, I realized that and have added an error message for it. Trying to find a copy of that file to test. I assume it's one we can't make available. We might be able to add the files in dropbox that pipipi0 need to GitHub downloads.
