### ISSUE TITLE
Fitting error underestimation

### ISSUE THREAD

**Issue by xiexinhai** [GooFit/GooFit#249]
There is possible underestimation of fitting errors when using FitManager.

A simple test:
Generate several (e.g. 300) Gaussian toy samples, and use GaussianPdf & FitManager to perform fit on each toy sample.
Then fitting results with errors for Gaussian 'mean' and 'sigma' can form pull distributions, and the pull distributions should be N(0,1) Gaussian distribution. 
However, when performing this test, sigma of the pull distributions are larger than 1 (about 1.4~1.5). This test tells us that there is possible underestimation of fitting errors.

(
Another test, generate a Gaussian toy. Perform Gaussian fit to this toy using GooPdf & FitManager or just TH1F->Fit(), respectively, and compare the fitting errors from two ways. It will be easily found that errors from TH1F->Fit() will be much larger than GooPdf & FitManager by a factor of 1.4~1.5.
)

I think this problem can be caused by the settings of Minuit2. I notice that in GooPdf.cu, the function calculateNLL() will return 2 * NLL, and this may not accord with maybe confidence level settings in Minuit2. When I modify it to returning just NLL, and the above simple test gives a normal N(0,1) pull distribution.

**Comment by JuanBSLeite** [comment]
Hi @xiexinhai ,

I had this same problem in an older version. GooFit is setting twice the same error definition for unbinned fits when it includes the factor 2 and set the FCNBase::up()=0.5. The FCNBase::up() when using this factor must be 1.0 . 

You need to remove the factor 2 in the function below. It must fix your errors.

 (GooFit/src/PDFs/GooPdf.cu):
`__host__ double GooPdf::calculateNLL() {
    GOOFIT_MAYBE_UNUSED fptype norm = normalize();
    GOOFIT_TRACE("GooPdf::calculateNLL calling normalize: {} (host_norm should be 1: {})",
                 norm,
                 host_normalizations.at(normalIdx + 1));

    if(host_normalizations[normalIdx + 1] <= 0)
        GooFit::abort(__FILE__, __LINE__, getName() + " non-positive normalization", this);

    // make this memcpy async
    host_normalizations.sync(d_normalizations);

    fptype ret = reduce_with_metric();
    GOOFIT_TRACE("GooPdf::calculateNLL calling sumOfNll = {}", ret);

    if(0.0 == ret)
        GooFit::abort(__FILE__, __LINE__, getName() + " zero NLL", this);

    return 2.0 * ret; //here
}`
