### ISSUE TITLE
Energy dependent resolution & convolution

### ISSUE THREAD

**Issue by DingXuefeng** [GooFit/GooFit#25]
Dear maintainers,

I'm trying to use GooFit in our studies. The resolution usually depend on the energy, say, 1/sqrt(E). or more complex models. In such cases the convolution becomes

covPdf(E) = \int_e1^e2 pdf(e) * res( e, E ) de.

the ConvolutionPdf has to be changed a lot. The size of the res_workspc should be changed to be much larger. Do you have plans to implement it?

thanks.

**Comment by henryiii** [comment]
Hi @DingXuefeng, we just had our first GooFit meeting of the year earlier today and this was brought up. We'd like to talk with you about your specific use case, would you be interested in a conversation? 

The latest version of GooFit (about to be merged) can have new PDFs added, and there is also development on Hydra to add more functionally like this (and Hydra may become the new backend for GooFit at some point)
