### ISSUE TITLE
CMake file

### ISSUE THREAD

**Issue by Xola101** [GooFit/GooFit#251]
Hi guys.

I am new to Goofit. I noticed that GooFit has its own CMake commands like goofit_add_package. I am trying to build an example from goofit_nips that has the same commands but my compiler is giving me the following errors:

```
CMake Error at CMakeLists.txt:1 (goofit_add_directory):
  Unknown CMake command "goofit_add_directory".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as
   cmake_minimum_required(VERSION 3.17)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/xola1/GooFit/examples/addition/CMakeFiles/CMakeOutput.log".

```

Is there something that I am missing because I have followed the build instructions to the T. I am however able to run the built examples in the package.

Thanks

**Comment by henryiii** [comment]
If you have GooFit as a sub directory, it should look like this:

```cmake
cmake_minimum_required(VERSION 3.9...3.16)

project(MyProj LANGUAGES CXX)
add_subdirectory(goofit)
goofit_external_package()

goofit_add_executable(MyExe MyExe.cu)
```

If, however, you want to put your package in GooFit's folder, then it looks like this (and the package folder **must** start with the name `goofit_`):

```cmake
goofit_add_package(MyProj ROOT)

goofit_add_executable(MyExe MyExe.cu)
```

**Comment by Xola101** [comment]
Hi thanks I used the first method and it works when I compile on terminal. However, I tried doing it on Clion but I get the following error in the attached .txt file. 
[error.txt](https://github.com/GooFit/GooFit/files/5154502/error.txt)

Is there no way to get projects to compile using Clion?

**Comment by Xola101** [comment]
Ok got it to work. Thanks
