### ISSUE TITLE
Preparing for release 2.0

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#26]
An official tagged release (to be called 2.0.0) will be made at some point in the near future. The following give general plans for the release and plans for the future. 

## Planned for 2.0
* [ ] Make a change log
* [ ] Look at removing the separate docs branch, and use docs in master (now supported in GitHub)
* [ ] Make datafiles more readily available

## Possible for 2.0
* [ ] Move from MCBooster to Hydra
* [ ] Set up tests, add Travis CI

## Work for 2.1+
* [ ] Improve separation of headers and source in PDFs
* [ ] Use some sort of parser in the examples to improve option descriptions

## Work for 3.0+
* [ ] Move the backend to Hydra, will add TBB

**Comment by hassec** [comment]
As discussed, I will go ahead and close this as we are moving to a roadmap in the wiki, connected with issues for every task.

this creates a place for discussion for each feature, and keeps them organized.
