### ISSUE TITLE
kMatrix crash in CUDA 11

### ISSUE THREAD

**Issue by danielsibemol** [GooFit/GooFit#287]
@henryiii, as we discussed last Friday, I have put the code I showed in our meeting in: **https://github.com/GooFit/GooFit/tree/daniel_CUDA11**
The example python code, provided by Martha, is also included inside the folder **kMatrix_test.** 

As a reminder, the code was crashing when entering the kMatrix function, we were able to print **pc** outside the function, but not inside the kMatrix function, not even pc's address. 

This was tested in sneezy, with cuda 11.2, driver version 460.73.01, gcc version 9.3.0. 

Compilation flags: 
**-DGOOFIT_FORCE_LOCAL_THRUST=OFF -DGOOFIT_CERNROOT=OFF -DGOOFIT_PYTHON=ON -DGOOFIT_KMATRIX=ON**

@mdsokoloff, @FlorianReiss, @marthaisabelhilton might also be interested in following this thread

**Comment by FlorianReiss** [comment]
not necessarily related to the crash, but one thing to understand is why the kMatrix implementation calls `initialize()`, while other resonances don't https://github.com/GooFit/GooFit/blob/master/src/PDFs/physics/resonances/kMatrix.cu#L166

**Comment by FlorianReiss** [comment]
#302 should fix one potential problem
