### ISSUE TITLE
Make datafiles more readily available

### ISSUE THREAD

**Issue by hassec** [GooFit/GooFit#29]

**Comment by henryiii** [comment]
The Dropbox hosted file is now in the GitHub releases, and is downloaded directly from there automatically by CMake.

**Comment by hassec** [comment]
I guess we can consider this as closed, right @henryiii ?

**Comment by henryiii** [comment]
No, still need to add one more file for zachFit. Need to figure out how to contact Zach.

**Comment by hassec** [comment]
Ah, ok sorry about that.

**Comment by henryiii** [comment]
That’s okay, I was careful about how I worded the mentions of issues in the pull request to close just the ones that were finished. :) From here on out I’ll try to brach, fix one thing, then merge.

Henry

**Comment by henryiii** [comment]
Done. :)
