### ISSUE TITLE
CI Configure failing

### ISSUE THREAD

**Issue by FlorianReiss** [GooFit/GooFit#311]
the CI Configure step started to fail with ` fatal: unsafe repository ('/github/workspace' is owned by someone else)` e.g. https://github.com/GooFit/GooFit/runs/6210970426?check_suite_focus=true

cc @henryiii

**Comment by FlorianReiss** [comment]
might be related to https://github.com/actions/checkout/issues/760

**Comment by henryiii** [comment]
I fixed this in #307, but that one had issues with convergence, and I wasn't sure if it might be related to the version bumps there. But the fix can be pulled out.
