### ISSUE TITLE
Problem installing GooFit with Cmake

### ISSUE THREAD

**Issue by AbrahamReyes** [GooFit/GooFit#35]
When I do 
cmake ../GooFit -DGOOFIT_ARCH=sm_35
 I got this:

-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /home/abraham/goofit_build/CMakeLists.txt
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.0") 
-- Auto device selection: CUDA
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.0") 
CMake Error at cmake/support_old_cmake/FindCUDA/select_compute_arch.cmake:142 (message):
  Unknown CUDA Architecture Name sm_35 in CUDA_SELECT_NVCC_ARCH_FLAGS
Call Stack (most recent call first):
  CMakeLists.txt:94 (cuda_select_nvcc_arch_flags)

CMake Error at cmake/support_old_cmake/FindCUDA/select_compute_arch.cmake:146 (message):
  arch_bin wasn't set for some reason
Call Stack (most recent call first):
  CMakeLists.txt:94 (cuda_select_nvcc_arch_flags)

-- Compiling for GPU arch: 
-- Activating GPU Arch 3.5+ features
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found ROOT: /home/abraham/root6-build/bin/root-config (Required is at least version "6") 
-- Configuring incomplete, errors occurred!
See also "/home/abraham/goofit_build/CMakeFiles/CMakeOutput.log".
See also "/home/abraham/goofit_build/CMakeFiles/CMakeError.log".

 I don't know what is the problem if I've installed ROOT 6 version v6-08. Can you help me please?
I'll apreciate.
Abraham

**Comment by henryiii** [comment]
CMake's error reporting isn't the greatest, it keeps going after an error. The problem is the Cuda part, the flag you are giving it. It should be `35`, not `sm_35`. The default (auto) will detect your card if you are compiling with access to the card.
Let me know if that works!

**Comment by henryiii** [comment]
PS: Try 3.5 if 35 or auto doesn't work, I'm using FindCUDA from CMake 3.7, it follows that convention.

**Comment by AbrahamReyes** [comment]
Yes it works with 3.5!!, thanks henry!!

**Comment by AbrahamReyes** [comment]
do I have to set any enviroment variable after installing?
I tried to run an example and I got this:
PARAMETER DEFINITIONS:
    NO.   NAME         VALUE      STEP SIZE      LIMITS
     1 mpv          4.00000e+01  1.50000e+01    0.00000e+00  1.50000e+02
     2 sigma        5.00000e+00  3.00000e+00    0.00000e+00  3.00000e+01
 **********
 **    1 **MIGRAD
 **********
 FIRST CALL TO USER FUNCTION AT NEW START POINT, WITH IFLAG=4.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  current_device(): after cudaGetDevice: unknown error
Abortado

**Comment by hassec** [comment]
Hi,

would you mind giving us a little more info about your system (OS, GPU, Nvidia driver)   

Also, did you install the examples that come with cuda 8.0? If so try running the example called `deviceQuery` which will merely print out some info about your card. But it is always a good test to see if your card/driver is setup correctly.

**Comment by henryiii** [comment]
Did the automatic selection of compute capability not work? NVIDIA's FindCUDA actually creates a tiny CUDA program and runs it to select the compute capability (basically the `deviceQuery` program @hassec mentioned); if that doesn't work, it's really unlikely that any CUDA program will run. Do you only have one card? Have you run any CUDA code on it before? GooFit does not require any env. variables to be set, but CUDA requires that the CUDA libraries be a directory in `LD_LIBRARY_PATH`.

**Comment by AbrahamReyes** [comment]
Ok, I'm working by ssh connection and the server have Scientific Linux release 7.3 (Nitrogen) installed.
Here is my $LD_LIBRARY_PATH
/home/abraham/root6-build/lib:/data/abraham/GooFit-Build/src/rootstuff:/usr/local/cuda/lib64

 I've tried to run deviceQuery example to get information about the GPU  but I get this:
 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 30
-> unknown error
Result = FAIL

I have to tell you that I don't know too much about FindCuda, When I started to work Cuda 8.0 was installed before I installed GooFit. Should I have to reinstall Cuda?

**Comment by henryiii** [comment]
That sounds like a graphics card driver issue. For example, [here's someone who had a similar issue](https://devtalk.nvidia.com/default/topic/760872/ubuntu-12-04-error-cudagetdevicecount-returned-30/).

If you either reinstall your graphics drivers or switch to the NVidia if you are using the generic one you should resolve the issue. Once CUDA works, GooFit should work fine.

PS: Feel free to try the OMP build of GooFit too, `-DGOOFIT_DEVICE=OMP`.

**Comment by henryiii** [comment]
Please let us know if you need help! Assuming you got it going.

There is now an `nvidia-docker` image at `goofit/goofit-cuda` (and a regular docker image at `goofit/goofit-omp` that can be used to provide a development environment. It still requires working drivers though, since `nvidia-docker` talks to the host drivers.
