### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#62]
I have a question: would using git submodules be a good idea? In PR #61, I start to use them for a small library that I wanted to add. If we do use submodules, I could use those to get CLI11, rang, and Thrust, so that they would not be downloaded for each build directory, and maybe GoogleTest. I might even move our fork of MCBooster to a submodule. This might handle updates (for example, to CLI11) a little better than the current system.

The downsides are the standard one for submodules, you have to use `--recursive` when cloning the repository, and/or it is helpful to know submodule commands, `git submodule update --init`, etc.

**Comment by henryiii** [comment]
@galapaegos, @hassec, any thoughts?

**Comment by galapaegos** [comment]
I like the idea of submodules, but I worry that non-specific versions of libraries will complicate code especially with API changes.  Is there a disadvantage to having each of the libraries downloaded to the root directory so that all builds can reference them, and appropriate checks for if it is already downloaded?

**Comment by hassec** [comment]
Generally speaking I think submodules are quite nice.   
But in a general purpose package like GooFit I feel like it's an necessary complication.     
I originally used it for MCBooster but moved away from it again.

**Comment by henryiii** [comment]
@galapaegos, submodules link to a specific commit and always checkout that particular commit. I *think* it is possible to reference a branch instead, but it's generally never done. So it is resilient to API changes; updating a submodule to a new commit is a change just like changing a file. (same set of issues as the current approach, really)

The only issue is that if a submodule repository is deleted, then you would have to upload it from a local copy. That's why I made a fork of the repository I used; I wouldn't worry about forks for major projects.

Yes, I could just make `AddX.cmake` download to `${PROJECT_SOURCE_DIR}/extern`, which honestly is a pretty good idea. If we refer to specific tags (I currently use master for CLI11 and maybe Rang), then I think updates might be handled properly there too.

@hassec Now we are dealing with more libraries, though: Thrust, MCBooster then Hydra, GoogleTest, Rang, CLI11.

Might even be possible to let CMake do the git submodule command...

**Comment by henryiii** [comment]
PS: Leaving this open for discussion, but I'll put it on my todo to download to `extern`.

**Comment by henryiii** [comment]
Simply telling CMake to checkout the submodules if they are not already checked out seems to work well, and covers both `/extern/*` and `/cmake` directories. It also works at configure time, so it works with IDE's (just like the `AddX.cmake`).

Does that work?

Example code that would be in the master CMake file:
```cmake

file(TO_CMAKE_PATH "${PROJECT_SOURCE_DIR}/extern/generics" GEN_PATH)
if(NOT EXISTS ${GEN_PATH})
    message(STATUS "Submodules not checked out, CMake will try to check them out for you")
    execute_process(COMMAND git submodule update --init --recursive
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    RESULT_VARIABLE GIT_SUBMOD_RESULT)
    if(NOT GIT_SUBMOD_RESULT EQUAL "0")
        message(FATAL_ERROR "git submodule update --init --recursive failed with ${GIT_SUBMOD_RESULT}, please checkout submodules")
    endif()
endif()
```

Personally, I really like this solution. Any thoughts?

**Comment by galapaegos** [comment]
@henryiii Thanks for the clarification, I haven't used submodules only read them.

I like this solution.
