### ISSUE TITLE
Separable compilation

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#69]
The AllPdfs (the old cuda-glob style combination) causes nvcc to segfault when building for Arch 6.0 (P100). Since the separable compilation method works, allows packages to add PDFs, and is cleaner, I'd like to remove this option. It's slower to build if you are building single threaded, so for now I might just make it no longer the default for CUDA builds.

**Comment by galapaegos** [comment]
I agree with making separate compilation a default for CUDA builds.
