### ISSUE TITLE
GooFit web page

### ISSUE THREAD

**Issue by cdeil** [GooFit/GooFit#7]
Should we try and set up a GooFit web page?

The easiest might be to use the same setup that thrust is using, i.e. github pages and the github wiki:
- http://thrust.github.io
- https://github.com/thrust/thrust/wiki

Googling "GooFit" shows quite a few nice talks with results and even just having a link collection would be very helpful.

**Comment by henryiii** [comment]
Docs are now rendered into a webpage by TravisCI. Linked in a couple of places.

**Comment by henryiii** [comment]
Added GooFit.github.io as well.
