### ISSUE TITLE
Compile Error, please help!

### ISSUE THREAD

**Issue by rhett533** [GooFit/GooFit#72]
Hi all!  I  compile the GooFit-0.3 with cuda-6.5 following the documentation.pdf in the GooFit-0.3 package, and copy thrust directory(1.6.0 version) to /usr/local/cuda-6.5/include.  But  errors occurs as follows:
GooFit-0.3/PDFs/DalitzPlotPdf.cu(160): error: calling a __device__ function("devcomplex") from a __host__ function("DalitzPlotPdf") is not allowed
GooFit-0.3/PDFs/DalitzPlotPdf.cu(236): error: calling a __device__ function("devcomplex") from a __host__ function("normalise") is not allowed
2 errors detected in the compilation of "/tmp/tmpxft_00006331_00000000-4_CUDAglob.cpp4.ii".

Then I try the newest version GooFit with cuda-8.0 and thrust-1.8.1, there is other error as follows:
CMake Error at CMakeLists.txt:206 (find_package):
  By not providing "FindThrust.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Thrust", but
  CMake did not find one.

  Could not find a package configuration file provided by "Thrust" (requested
  version 1.8) with any of the following names:

    ThrustConfig.cmake
    thrust-config.cmake

  Add the installation prefix of "Thrust" to CMAKE_PREFIX_PATH or set
  "Thrust_DIR" to a directory containing one of the above files.  If "Thrust"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/jiangt/soft/GooFit-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/jiangt/soft/GooFit-master/build/CMakeFiles/CMakeError.log". 

I find there isn't ThrustConfig.cmake or thrust-config.cmake in the thrust-1.8.1 package,  and i has tried 
to search on the WEB for some useful information buf find nothing about the errors above.
Any help will be appreciated ! Thanks!

**Comment by henryiii** [comment]
Hi! That is a known problem with the older versions of GooFit; GooFit 2.0 beta has removed `devcomplex` and uses `thrust::complex` instead. If you are going to use classic GooFit I'd at least use version 1.0.0, and maybe even the last makefile tag.

I'd love to have you help test the beta for GooFit 2.0; the final release of GooFit 2.0 is set for June 1st, so I'm trying to work out any of the final bugs. There is one last major patch that I'm hoping to merge in the next few days (makes Variable better & more like RooFit).

GooFit supplies `FindThrust.cmake` through `GooFit/cmake`, which is a git submodule. If you have the latest version CMake *should* download this for you, but you can do it yourself with `git submodule update --init --recursive`, **or** by adding the `--recursive` flag when you clone the repository. Please use `git pull` before this just to make sure you are on the latest version.

**Comment by henryiii** [comment]
And the latest version of GooFit has it's own download of Thrust, as well, also as a git submodule. You do not need to download it. You only need a recent CMake and two optional prerequisites, CUDA and ROOT. GooFit will build for OpenMP if it can't find CUDA, and will use a standalone Minuit2 (still working out possible bugs with that) if it can't find ROOT.

Technically with Thrust, it will use the version inside CUDA 7 or 8, and only uses it's copy if CUDA is not found.

**Comment by rhett533** [comment]
Hi henryiii, thanks!  I'll try tomorrow,  and I'd love to use the GooFit 2.0.  If there  is any question, I will send messsage to you soon.  Good luck!

**Comment by henryiii** [comment]
Okay, great; I'm happy to help. If we are lucky maybe the variable patch will be done before then.

**Comment by henryiii** [comment]
The IO and Variable patch has been merged. You can now use GooFit master. Were you able to get it working?

**Comment by rhett533** [comment]
Hi henryiii,   yes, it works, thank you!  I will try the new version later. Good Luck!

**Comment by henryiii** [comment]
Great, let us know if you encounter any problems! GooFit 2.0 should be final a week from today.
