### ISSUE TITLE
Expand Python bindings to Minuit2

### ISSUE THREAD

**Issue by henryiii** [GooFit/GooFit#95]
This could be done to provide iMinuit2, too. Thoughts that need solutions:

* [x] How to set this up so that it could be used directly or from another python binding system (GooFit, in this case).
* [ ] How this would interact with user-supplied functions, python and cython/numba/etc. Maybe look at iMinuit for inspiration?
* [x] Build system might need to be supplied with traditional python one instead of CMake to make more generally installable (the build system is pretty trivial and doesn't need external libs and CUDA like GooFit). If prerequisites can be specified for scikit-build, then this is not as important.

**Comment by thboettc** [comment]
Closing this, as there hasn't been any activity recently.
